name: trinity_lecture_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <=3.16.1"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  hydrated_bloc: ^9.1.2
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  bloc: ^8.1.2
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  fluttertoast: ^8.2.4
  json_annotation: ^4.8.1
  injectable: ^2.3.2
  get_it: ^7.6.4
  auto_route: ^7.8.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  freezed: ^2.3.3
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
